

import type { Metadata } from "next";

import "./globals.css";
import { CollaborationNotifier } from "@/app/(dashboard)/_components/collaboration-notifier";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { Toaster } from "sonner";
import { ModalProvider } from "@/providers/modal-provider";

import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider>
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>

        <ConvexClientProvider>
            <Toaster position="bottom-right" richColors closeButton />
            <ModalProvider />
            <CollaborationNotifier />
            {children}
        </ConvexClientProvider>
        
      </body>
    </html>
  </ClerkProvider>
  );
}
